### ISSUE TITLE
`subfiles` determination is broken in case `\subfile{..outer/relative/path.tex}` is used

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#1144]
`vimtex` fails to determine the path and main file, when a subfile is located in the outer directory. This particular directory structure for example is used in case of presentations with common frames folder:
```
frames_common/
talk1/frames -> frames_common
talk2/frames -> frames_common
talk3/frames -> frames_common
```
Each frame is located in a separate tex file, included via subfile. 

1. A minimal `vimrc` file for neovim:

    ```vim
    filetype plugin indent on
    set runtimepath^=~/.config/nvim/bundle/repos/github.com/lervag/vimtex
    set nocompatible
    ```
    latest `vimtex` snapshot from github.

2. A minimal `.tex` file:

    ```tex
    \begin{filecontents}{sub/abs.tex}
      \documentclass[test.tex]{subfiles}
      \begin{document}
      currend WD
      \end{document}
    \end{filecontents}

    \begin{filecontents}{lsub/abs.tex}
      \documentclass[test.tex]{subfiles}
      \begin{document}
      outer WD
      \end{document}
    \end{filecontents}

    \documentclass{report}
    \usepackage{subfiles}
    \begin{document}
    \subfile{sub/abs.tex}
    \subfile{lsub/abs.tex}
    \subfile{../sub/abs.tex}
    \end{document}
    ```

    Before running latex in a working directory `WD` create folders:
    1. `WD/sub`
    2. `WD/../sub`
    3. A symbolic link `WD/lsub` pointing to `../sub`

3. Steps to reproduce:
    a. In `WD` execute `nvim -u init_minimal.vim test.tex`
    b. Position cursor on first subfile `sub/sub.tex`, press `gf`, then `\li` to check that the main file is determined correctly.
    c. Go back. Position cursor on the second subfile `lsub/sub.tex`, `gf`, `\li`. See that the main file is not determined. 
    d. Go back. Position cursor on the second subfile `../sub/sub.tex`, `gf`, `\li`. See that the main file is not determined. 

4. Expected behavior. The main file is expected to be determined in all the cases. I'm using  such a directory structure for my talks for a long time. I do not remember when I've updated the vimtex before, but as far as I can say in December 2017 for all the cases the main file was determined correctly.

**Comment by lervag** [comment]
Hi. I've reproduced the issue, but I am not able to find any point in history where this works.

I actually think I decided once that this is too difficult to fix reliably. There are two cases:

1. The user does not use `autochdir` (default). In this case, one could assume that the users working directory is the same as the main file working directory, and so this can be used to search for the main file. I think this could work in many cases, however, it rests on an assumption that really may not be true. If it is not true, then there is no way of knowing in a reliable manner where the correct main file is.

2. The user does use `autochdir`, in which case one can not know where the main file is. An easy example:

    ```    outer/sub.tex
    inner1/test.tex
    inner2/test.tex
    ```

    Assume that you open `inner1/test.tex`, then open `outer/sub.tex` through the `gf` keys. However, since we can not trust `getcwd()`, there is no longer any reliable manner to differentiate `inner1` from `inner2`.

One possible solution is to determine this from the previous file. That is, say you open an outer `abs.tex` from some main file that includes it. We could try to make some heuristic to connect the outer subfile to the alternate buffer. It could be something like this:

1. Open subfile in Vim (with `\documentclass[...]{subfile}`)

2. If it does not find a "parent" main file, then check if there is an alternate buffer, and if this alternate buffer is a vimtex buffer.

3. If it is a vimtex buffer, then check it's data for the `source files` and see if the new file is listed here. If it is, then we make the connection.

**Comment by lervag** [comment]
I've implemented my suggested solution, which I think should work fairly well in your case. Note however that this only works if you open the outer subfile after you open a file in the main project that is detected properly.

**Comment by maxfl** [comment]
@lervag, thank you for the quick fix. Now the main file is now determined correctly.

One problem still persists though. When switched to the local mode via '\ls' the directory of the main file is not kept in case of the relative outer link. So, `\ls` for 3b works, whild 3c and 3d fail.

**Comment by lervag** [comment]
Thanks, I think this should be fixed now as well.

**Comment by maxfl** [comment]
works. Thank you!

**Comment by lervag** [comment]
No problem, and thanks for contributing by opening issues!
