### ISSUE TITLE
New indentation on ampersand implementation leads to misalignment

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1244]
After merging PR #1204 I see misaligned environments on indentation (gg=G), apparently if the beginning or end statements have trailing spaces. Here are two examples (that may not work in isolation):
```tex
    \begin{equation*} 
        \left \{ 
            \begin{aligned}
                -\Delta \theta &= u \quad \text{in } \Omega, \\
                \theta &=0 \quad \text{on } \Gamma.
            \end{aligned}
        \right.
\end{equation*}
```
(trailing spaces after `\begin{equation*} `  and `\left \{ `) and
```tex
    \begin{equation} \label{eq:state2}
        \left\{
            \begin{aligned}
                -\div [a_M(z)\nabla y + b(\nabla y)]  &= u \quad \text{in } \Omega, \\
                y &=0 \quad \text{on } \Gamma.
            \end{aligned}
        \right.
\end{equation}
```
(obvious trailing space after `\begin{equation}`, before `\label`). Removing these allows correct indentation. Letting `g:vimtex_indent_on_ampersands=0` also restores correct indentation.

Seems related to #1243.

**Comment by lervag** [comment]
I've added test files, and I do see something strange that I'll investigate, but I don't see that the exact examples are indented incorrectly. (Instead, I see that in my minimal.tex example, the last line `\end{document}` is for some reason indented a single space. That does not make much sense, and I'll investigate as soon as possible.)

**Comment by clason** [comment]
Yes, I observed something similar -- the examples are indented incorrectly in their original context and when I yank and paste them into a new buffer (i.e., they stay incorrectly indented after `gg=G`), but retyping the same example into a new file (or copy&pasting it via the system clipboard), they are indented correctly. Very strange.

**Comment by lervag** [comment]
I think I've fixed this. Note, though, that I did it by anchoring some regexps to the beginning of line. I hope this makes for a reasonable assumption, but I am not sure. In any case, I understand the problem, and if the assumption does not hold generally enough, then, with a good MWE, I should be able to improve it.

I also believe this might fix #1243, so please test.

**Comment by clason** [comment]
That looks better, but still shows some problems (like the misindented `\end{document}`). The assumption on `\begin` starting lines fails for more complicated alignment constructs like
```tex
\begin{equation}
    \left\{
        \begin{aligned}
            \min_{u,y} &J(u,y) \\
            \text{s.t.} \quad
            &\begin{aligned}[t]
                -\Delta y &= u && \text{in } \Omega\\
                y &= 0 && \text{on } \partial\Omega.
            \end{aligned}
        \end{aligned}
    \right.
\end{equation}
```

**Comment by lervag** [comment]
Hmm, interesting example! Challenge accepted :)

**Comment by lervag** [comment]
Ok, it seems that things work well if I relax the anchoring. I'm not 100% sure if this always works, but I think for well structured documents, it should work. Please test again.

**Comment by clason** [comment]
Time to get out the reg exp playbook, is it? :)
>  for well structured documents,

Challenge accepted :)

1. There's no ampersand alignment in `cases` environments (although otherwise the alignment is correct).
2. There's a misalignment inside `tabular` environments if the alignment options aren't in the same line:
```tex
\begin{tabular}{%
              ccc}
...
\end{tabular}
```
(and no alignment on ampersands). This is useful for siunitx's `S` columns with long formatting options.
3. The `\end{document}` is still misaligned. 

Performance is still 1.12s (no amp alignment) vs. 4.25s (amp alignment) with 167667 hits on `while l:lnum >= 1` (same file as before, but different machine).

**Comment by lervag** [comment]
Great! Can you give me examples of what you consider to be "correctly indented" 1) `cases` evironment and 2) `tabular` environment with multline option? Also, a minimal example where the `\end{document}` is misaligned?

> Regarding 2: What is the intention for multiple alignment points? Is only the first supposed to be aligned, or all of them? What about the column separators &&?

Not quite sure what you are asking. That is, what do you mean with "multiple
alignment points"? Examples would be great!

> Performance is still 1.12s (no amp alignment) vs. 4.25s (amp alignment) with 167667 hits on while l:lnum >= 1 (same file as before, but different machine).

I still think/hope this is due to the same problem as you see with your third issue. If you have multiple cases that fail for some reason, then I would not be surprised if these cases end up looping through most of your document.

If you are able to find an example of a long manuscript that takes a long time to indent that is in the public domain, then that could be used as an example while improving the indent performance?

**Comment by lervag** [comment]
As far as I can tell, all of these examples indent correctly with the latest version. Could you clarify what I'm missing here?

I'll take a look at the paper manuscript when I get the time, perhaps that will make some things clear to me.

**Comment by clason** [comment]
Oh, yes, they're not meant as failing examples, just illustrating the environments. To test the indent routine,  the lines shouldn't naturally align (replace `1` with `-1` for one and `e` with `-e` and similarly for `g` to see what I mean; for 2., you also need to have the alignment option `ccc` on another line).

**Comment by lervag** [comment]
Ok, so, for multiple alignment points, I guess you mean aligning as a table on `&`s, right? That's not a feature provided; only indentation is provided. For tabular alignments, you should look into something like [vim-easy-align](https://github.com/junegunn/vim-easy-align).

The indentation is not going to be smart enough to e.g. ignore the minus. In such cases, you need to use something like vim-easy-align or a more fully feature LaTeX formatter.

The main point of the indent function is to provide something that is very close to "good enough", IMHO. I am not aiming for perfect. And so, there will be things like this that I will not aim to support.

Back to your examples, I still don't quite see the difference between what you expect and what is observed. E.g. for continued options for tabular, I think the current behaviour seems OK.

**Comment by clason** [comment]
That's what I meant about not being sure multiple alignments being intended (pun as well). 

But here's a concrete example of a not aligned cases environment:
```tex
\begin{equation*}
    a_M(y):=
    \begin{cases}
        a(M) &\text{if } y>M,\\
        a(y) &\text{if } |y|\leq M,\\
        a(-M) &\text{if } y<-M.
    \end{cases}
\end{equation*}
```
Or did I misunderstand the feature and only *leading* ampersands are aligned (with the first, non-leading one)? In that case, ignore those comments.

But the tabular thing is in fact misaligned:
```tex
\begin{tabular}{%
    ccc}
        1 & 2 & 3 \\
        4 & 5 & 6
    \end{tabular}
```
It's correct if I put the `ccc}` on the same line as the `\begin{tabular}{`.

**Comment by lervag** [comment]
> Or did I misunderstand the feature and only leading ampersands are aligned (with the first, non-leading one)? In that case, ignore those comments.

Yes, exactly: Only _leading_ ampersands are aligned. Perhaps this is worded confusingly in the documentation?

I can reproduce the tabular thing, so I'll look into how to fix it.

**Comment by lervag** [comment]
Do you agree that this is the correct indentation (given `&sw = 2`):

```
\begin{tabular}{%
  ccc}
  $a$ & $b$ & $c$ \\
  $d$ & $e$ & $f$
\end{tabular}
```

**Comment by clason** [comment]
Yes; the alignment should be relative to the head (`\begin{tabular}`), not the foot ( `ccc}`) of the environment start.

**Comment by lervag** [comment]
Ok, try now. The main idea behind the indentation function is that we always assume that the previous line is correctly indented. In some cases, we need more context, but in most cases, it suffices to look at the current and the previous line. Instead of trying to parse the "meaning" of the `\begin{...}` command, I instead fixed the latter case by allowing `\end{...}` to look at the previous line to induce the correct indentation.

I would not be surprised if there are more cases that are still incorrect, but I think we can solve most cases similar to how I've implemented it now.

Feel free to open more issues (or continue discussion here, if more appropriate) if you have more misaligned cases!

**Comment by clason** [comment]
Yep, that fixes the tabular example! The only thing that's still off is the `\end{document}` being indented by itself -- I've narrowed it down to the following (inside a `proof` environment):
```tex
$B \begin{psmallmatrix} \delta w \\ \delta \psi \end{psmallmatrix} = \begin{psmallmatrix} r_1       \\ r_2 \end{psmallmatrix}$
```

**Comment by clason** [comment]
> Ok, so, for multiple alignment points, I guess you mean aligning as a table on &s, right? That's not a feature provided; only indentation is provided. For tabular alignments, you should look into something like vim-easy-align.

By the way, I use https://github.com/godlygeek/tabular, which is pretty basic but completely sufficient for formatting LaTeX tables. I'll have to take a look at easy-align.

**Comment by clason** [comment]
OK, that *is* pretty neat -- I'll try it out! (Does the `EasyAlignRepeat` play nice with tpope's vim-repeat?)

And thanks for fixing all the weird examples!

**Comment by lervag** [comment]
Yes, I think it does. From the help file:

> Notice that the commands are repeatable with `.` key if you have installed {repeat.vim}{3}. Install {visualrepeat}{4} as well if you want to repeat in visual mode.

And no problem, I'm glad I have people like you who raise thees issues, because it makes it much easier to find and fix the bugs and problems! :)
