### ISSUE TITLE
Undefined variable: b:current_syntax

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#141]
I've been getting this error for a while, I guess it's about time to report it... Every time I open a .tex file, this error pops up. I don't use dot so for me it can be solved by commenting out the block of lines 46-57 in `vimtex/after/syntax/tex.vim`, but obviously that disables some functionality. Perhaps some checks are missing?
```
Error detected while processing /home/lahwaacz/.config/vim/bundle/vimtex/after/syntax/tex.vim:
line   46:
E121: Undefined variable: b:current_syntax
E15: Invalid expression: b:current_syntax
line   47:
E108: No such variable: "b:current_syntax"
line   57:
E121: Undefined variable: s:current_syntax
```

**Comment by lervag** [comment]
Should be fixed now, please test. I agree, one should check that the variable exists before using it.

**Comment by lahwaacz** [comment]
Well, it did not fix it for me: when I open any `.tex` file, it is not highlighted and `:echo b:current_syntax` returned `dot`.

In the meantime I discovered that the real problem was misconfigured `runtimepath` (`$HOME/.vim/after` before `$VIM/vimfiles/after`) on my side, so with `runtimepath` properly configured even the original version without any checks works fine.

One more question, is `vimtex/after/syntax/tex.vim` loaded also for other file types than `tex`? I mean, the current state is not perfect because under certain conditions `dot` can end up in `b:current_syntax` when it shouldn't, so if `tex` is the only valid type for this syntax file, you could simply `unlet b:current_syntax`, load dot region and then `let b:current_syntax = 'tex'`.

**Comment by lervag** [comment]
I see. I'll revert the improper fix then. And I agree that `b:current_syntax` should be `tex`, which can be used to simplify slightly.

**Comment by lahwaacz** [comment]
The last commit looks good, thanks. And sorry for the earlier misinformation.

**Comment by lervag** [comment]
No problem!

ons. 1. apr. 2015, 19.04 skrev Jakub Klinkovský <notifications@github.com>:
