### ISSUE TITLE
Syntax highlighting broken after backward syncing

### ISSUE THREAD

**Issue by Krasjet** [lervag/vimtex#1457]
**Issue**
Superscripts(^) and subscripts(_), etc. in math environments show up as invalid after backward syncing from zathura.

**minimal.vim**
  ```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_view_method = 'zathura'

if has('nvim')
    let g:vimtex_compiler_progname = 'nvr'
endif

nnoremap q :qall!<cr>
nnoremap e :echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')<cr>

silent edit minimal.tex
```

**minimal.tex**
Here is a much simpler file to debug with.
  ```tex
\documentclass[12pt]{article}
\usepackage{amsmath}

\begin{document}

\begin{align*}
    \vec{u} = \begin{bmatrix}
        3\\1
    \end{bmatrix}
\end{align*}

\begin{align*}
    \sigma_{\vec{u}} = \sqrt{\sum_{i=1}^N (u_i - \mu_u)^2}
\end{align*}
\end{document}
  ```

**Commands/Input**
1. Close any existing zathura windows
2. nvim -u minivimrc
3. Run ":VimtexCompile". Wait until zathura pops up.
4. Ctrl+click on any formula in zathura, and make sure the document in vim correctly is synced to the correct position.
5. Observe the highlighting of any ^ and _ in align* environment

**Observed Behaviour**
![pic-selected-190823-0852-24](https://user-images.githubusercontent.com/5229241/63594644-019e8900-c585-11e9-95dc-d86de485045e.png)

**Expected Behaviour**
Probably something similar to this.
![pic-selected-190823-0903-04](https://user-images.githubusercontent.com/5229241/63594696-2266de80-c585-11e9-940a-4e9f5fc76a25.png)

**Output from VimtexInfo**
```
System info
  OS: Arch Linux
  Vim version: NVIM v0.4.0-1792-gc6eb1f42b
  Has clientserver: true
  Servername: /tmp/nvim

vimtex project: test3
  base: test3.tex
  root: /home/krasjet/tmp/highlight
  tex: /home/krasjet/tmp/highlight/test3.tex
  out: /home/krasjet/tmp/highlight/test3.pdf
  log: /home/krasjet/tmp/highlight/test3.log
  aux: /home/krasjet/tmp/highlight/test3.aux
  fls: /home/krasjet/tmp/highlight/test3.fls
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimJQyUB9/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    pid: 0
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"nvr --servername /tmp/nvim --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'test3.tex'
  viewer: Zathura
    xwin id: 44040195
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: article
  packages:
    amsbsy
    amsgen
    amsmath
    amsopn
    amstext

```

**Comment by lervag** [comment]
Thanks! I've reproduced this and will look into it when I get the time. I'm busy this weekend, so I think it will be sometime next week, perhaps Monday.

**Comment by lervag** [comment]
Ok, thanks. I think I've fixed this now.

**Comment by lervag** [comment]
Yes, you are right. I don't know why, but my initial fix only worked on some (random) tests. I've implemented a more hackish solution that seems to work well.

**Comment by Iambecomeroot** [comment]
I am still experiencing this weird highlighting, though I am not using backward syncing (I have not configured it, anyways). The highlight group on the `_` characters is `hi<texOnlyMath> trans<texOnlyMath> lo<Error>`.

`:VimtexInfo`: https://pastebin.com/7iHRirH7

Is this related or should I open a new issue?

**Comment by lervag** [comment]
> though I am not using backward syncing (I have not configured it, anyways).

Well, then, you are not experiencing _this_ weird highlighting. So please open a new issue with a full description.

**Comment by lervag** [comment]
Note: Even if it is related to #1099, please open a new issue. It makes it much easier for me.

Note 2: No reason to use pastebin instead of attaching output inside fenced code blocks (```` ``` ... ``` ````).

**Comment by Iambecomeroot** [comment]
What I mean by that is the solution from #1099 (moving tikz code after `\begin{document}`) worked for me and resolved the issue. As cloudhead said, sorry for the noise.

Sorry for not using code blocks too. I didn't want to post long code blocks in the comments.

**Comment by lervag** [comment]
No problem! :)
