### ISSUE TITLE
Section navigation ([[ and ]]) appear to be broken (i.e. finds any mention of section or subsection even within comments)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1470]
The `[[` and `]]` motions (and their counterparts, `[]` and `][`) which have been around in `vimtex` for a long time seem to have an issue. Instead of restricting the navigation to `\begin{somesection} ...\end{somesection}` sequence, it navigates to every instance of the particular keywords `section` and `subsection`.  I stumbled upon this by accident when trying to navigate through the long & heavily commented default `.tex` file supplied as part of `IEEEtran` template.

Here's an excerpt from that file which illustrates the problem.

```
\section{Conclusion}
The conclusion goes here.




% if have a single appendix:
%\appendix[Proof of the Zonklar Equations]
% or
%\appendix  % for no appendix heading
% do not use \section anymore after \appendix, only \section*
% is possibly needed

% use appendices with more than one appendix
% then use \section to start each appendix
% you must declare a \section before using any
% \subsection or using \label (\appendices by itself
% starts a section numbered zero.)
%


\appendices
\section{Proof of the First Zonklar Equation}
Appendix one text goes here.

% you can choose not to have a title for an appendix
% if you want by leaving the argument blank
\section{}
Appendix two text goes here.


% use section* for acknowledgment
\section*{Acknowledgment}


The authors would like to thank...
```

**Comment by lervag** [comment]
> Instead of restricting the navigation to \begin{somesection} ...\end{somesection} sequence, it navigates to every instance of the particular keywords section and subsection.

Hmm. No, I'm not sure I fully agree. `[[` and friends navigate between sections and parts, i.e. `\section`, `\subsection`, etc. Not `\begin{..} \end{..}` pairs.

However, I do agree that your example illustrates that the motions do not ignore the contents of comments.

Just to be sure: Given your example, open Vim (with vimtex) on line 1 column 1. What is the expected positions (in your opinion) when you navigate through the document with `]]`?

**Comment by krishnakumarg1984** [comment]
This is where I'd like the cursors to go for `]]`

```
\section{Conclusion}   % <----------------- start location
The conclusion goes here.




% if have a single appendix:
%\appendix[Proof of the Zonklar Equations]
% or
%\appendix  % for no appendix heading
% do not use \section anymore after \appendix, only \section*
% is possibly needed

% use appendices with more than one appendix
% then use \section to start each appendix
% you must declare a \section before using any
% \subsection or using \label (\appendices by itself
% starts a section numbered zero.)
%


\appendices <---------------- 1st ]]
\section{Proof of the First Zonklar Equation} <---------- 2nd ]]
Appendix one text goes here.

% you can choose not to have a title for an appendix
% if you want by leaving the argument blank
\section{}  % <------------3rd ]] 
Appendix two text goes here.


% use section* for acknowledgment
\section*{Acknowledgment} <---------- 4th ]]


The authors would like to thank...
```

In the latest `vimtex` version at the time of my original issue-report, `]]` merely acted as a simple non-highlighted search for one of these keywords (section, appendix, subsection).

**Comment by lervag** [comment]
I think it is fixed now.

**Comment by krishnakumarg1984** [comment]
@lervag thanks a lot for your support. The issue is not really fixed. The old behaviour persists, for example trying the same code in the issue report, the problems are noted below.

```

\section{Conclusion} % <--------------initial position
The conclusion goes here.




% if have a single appendix:
%\appendix[Proof of the Zonklar Equations]   % < ----- after ]] cursor moves here which is a commented line
% or
%\appendix  % for no appendix heading  % < ----- then, after next  ]] cursor moves here
% do not use \section anymore after \appendix, only \section*  % < ---- cursor is placed at \section, \appendix, \section* for every ]]
% is possibly needed

% use appendices with more than one appendix
% then use \section to start each appendix % < ---- next location
% you must declare a \section before using any % < --- now here
% \subsection or using \label (\appendices by itself % <---- stuck in \subsection. Weirdly misses \appendices          % <----- cursor does not stop here at all!
% starts a section numbered zero.)
%
```

Also wondering why the `]] missed `\appendices` entirely? Is this a separate bug (as in \appendices is not recognised as a section marker, while \appendix is)?

**Comment by lervag** [comment]
I suspect that you have not properly updated vimtex. Could you check that you are on the following revision:

```
rev:     708eb29
date:    2019-09-03 22:08:04
message: Fixed #1470: Improve [[ like motions
```

**Comment by krishnakumarg1984** [comment]
@lervag Aah. Indeed, my mistake. I had done a `:PlugUpgrade`, but didn't reopen `vim`. It's all fixed now. Thanks for your support on this.

**Comment by lervag** [comment]
Great, and no problem :)
