### ISSUE TITLE
quickfix ignore_filters not filtering .bib warnings

### ISSUE THREAD

**Issue by piperfw** [lervag/vimtex#1569]
**Issue**

Attempting to cite, for example, an article "test" in a `.bib` file which is missing a "title" entry will lead to the following warning on compilation: 
```
example.bib|1 warning| Missing "title" in "test"
```

The documentation suggests that the setting
```
let g:vimtex_quickfix_latexlog = {
          \ 'ignore_filters': ['Missing "title"']
        \}
```
should prevent any 'Missing "title"' warnings from being displayed in the quickfix window, yet with this setting they still appear. Have I done something wrong or do the filters not work with messages from `.bib.` files? I can upload a MWE if it is helpful. 

**Related Issues** (for information only): #1407, #1408

**Comment by lervag** [comment]
Actually, the documentation does not state that directly, and the current status is that you can not ignore the bibtex warnings. Thus, this needs to be implemented. I see two ways forward:

1. Move the ignore filter feature into a more general feature that applies to any source of quickfix entries. Currently, the ignore filter is only implemented specifically for errors from parsing the latex log, which explains the option name `g:vimtex_quickfix_latexlog.ignore_filters`.

2. Add ignore filters for bibtex and biblatex in a similar fashion as exists now for latexlog. This would add option dictionaries like `g:vimtex_quickfix_bibtex` with a similar `ignore_filters` entry.

The second way is most straightforward, and I think perhaps also better, as it gives more fine grained possibility for customization.

**Comment by piperfw** [comment]
Thanks for clarifying that. The second option seems pragmatic. 

Perhaps you could expand upon `g:vimtex_quickfix_blgparser` so that it more closely resembles `g:vimtex_quickfix_latexlog`; namely with both the `default` (the current use of `disable` feels less consistent) and `ignore_filters` entries.

**Comment by lervag** [comment]
Thanks for the input. I decided to clean up the quickfix/error interface a little bit, and ended up going for the first option. It was not so much work, and I think it is better.

Let me know what you think!

> Perhaps you could expand upon g:vimtex_quickfix_blgparser so that it more closely resembles g:vimtex_quickfix_latexlog; namely with both the default (the current use of disable feels less consistent) and ignore_filters entries.

The reason this was added as a dictionary was that I thought it could become interesting to allow more customization. This has not happened. The `disable` key is more "general" than the "default" key for the latexlog parser. Thus, I don't want to change this. I think it is more appropriate to instead "degrade" the option into a boolean flag, perhaps naming it `g:vimtex_quickfix_blgparser_enable`. Still, not sure if it is any real point in doing it. :\

**Comment by piperfw** [comment]
> Let me know what you think!

Excellent, I've just tried it out and works exactly as one would expect - thanks! 

> Still, not sure if it is any real point in doing it. 

Yes, it doesn't seem too important either way.

Should we close this issue?

**Comment by lervag** [comment]
> Yes, it doesn't seem too important either way.

Great, then we agree on this.

> Should we close this issue?

Yes, it seems the issue is solved. Thanks for reporting!

**Comment by hwalinga** [comment]
Not sure how to use this, I have

```
let g:vimtex_quickfix_ignore_filter = [
  \ 'Missing',
  \]
```

in my .vimrc but I still see

```
main.bib|273 warning| Missing "journal" in "example"
```

What am I missing?

**Comment by lervag** [comment]
> What am I missing?

You're missing a minor triviality: the option is named `g:vimtex_quickfix_ignore_filters`, notice the `s` at the end. ;)

**Comment by GersiD** [comment]
Hi all, I have the following code in lua, which correctly silences the errors from the Vimtex quickfix menu.

```lua
-- Lets silence some errors :)
vim["g"]["vimtex_quickfix_ignore_filters"] = {
  "Underfull",
  "Overfull",
}
```

However, I still see the diagnostics on the line where the errors are. Is this an LSP issue? I am currently using VimTex, Ltex, and Texlab. (I know all at once). My question is I know that when I detach Texlab from the file, the warning goes away, but so do all other warnings. I want to keep some warnings, just not particularly that one.

Possible dumb question (and I am late to the party on this one) but is this a VimTex thing? Like does VimTex report the errors to Texlab? I am a bit confused if I can even configure this.

Thank you!

**Comment by GersiD** [comment]
I re-wrote the above script using a command call to vimscript and it still yields the same result. Vimtex does not show the error in the quick fix but Texlab insists there is an issue. 

```lua
vim.cmd [[
  let g:vimtex_quickfix_ignore_filters = [
  \'Underfull',
  \'Overfull',
  \]
]]
```

Its likely that Vimtex and Texlab don't communicate. Thats why one shows the warning while the other doesn't.

**Comment by lervag** [comment]
> I am currently using VimTex, Ltex, and Texlab. (I know all at once). My question is I know that when I detach Texlab from the file, the warning goes away, but so do all other warnings. I want to keep some warnings, just not particularly that one.
> 
> Possible dumb question (and I am late to the party on this one) but is this a VimTex thing? Like does VimTex report the errors to Texlab? I am a bit confused if I can even configure this.

VimTeX does not communicate with Texlab or other LSPs. The VimTeX options only
control VimTeX.

Texlab will probably provide similar features as VimTeX with regards to compiling and parsing the errors from the log file. For all I know, it may be even better. But you can't control it with VimTeX options, you need to learn how to control Texlab by reading the Texlab docs or asking devs/users. I don't use it and don't know much/anything about it, sorry.

> I re-wrote the above script using a command call to vimscript and it still yields the same result.

Yes, the two variants are 100% equivalent.
