### ISSUE TITLE
gf fails if white space before expression

### ISSUE THREAD

**Issue by HawkinsT** [lervag/vimtex#1679]
**Issue**
On Windows 10 (not tested on other OSs), `gf` fails if the line starts with white space, so for example:
```tex
\include{example.tex}
    \include{example.tex}
```
the first line works and takes you to example.tex as expected. Hitting `gf` on the second line, however, returns:

```
Error detected while processing function vimtex#include#expr[33]..<SNR>144_search_candidates_texinputs:
line    2:
E219 Missing {.
E447 Cannot find file "-1" in path
```

Narrowing down the error, the function, `s:input` on line 59 of `autoload/vimtex/include.vim` returns a blank filepath/name here, which appears to be due to an error in [`vimtex#cmd#get_at`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/cmd.vim#L546-L552) ([invoked on line 63](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/include.vim#L63)), which returns `{}`, but I'm afraid I don't understand what this function's doing, so this is where my debugging's ended.

**Comment by lervag** [comment]
Thanks, I think this is fixed now.

**Comment by HawkinsT** [comment]
Thanks. This _mostly_ fixes the issue, however the error will still occur if the cursor is on the white space before the command. If the cursor is anywhere from the backslash (in, e.g. `\input{example}`) on, the action now completes successfully.

**Comment by lervag** [comment]
Actually, I think this is to be expected. `gf` does not work linewise, but works on the path (or in this case, "object") under the cursor. In general, you would move your cursor to the actual path when you use `gf`, but I've implemented support to make it possible to use `gf` on the tex macros as well.

Note: I did think about this and whether it would be possible to allow `gf` to work on the whitespace infront. I realize that `gf` on the whitespace in front of a path in general works as you expect. However, I was not able to find a good way of solving this. Sorry.

**Comment by HawkinsT** [comment]
No problem; thanks for taking the time to look.

My thinking with my previous comment was more that vimtex should handle the error better since it still displays:
```
Error detected while processing function vimtex#include#expr[33]..<SNR>144_search_candidates_texinputs:
line    2:
E219 Missing {.
E447 Cannot find file "-1" in path
```
If it's not an easy fix or you consider this error appropriate, I don't see it as a big concern though, since, as you say, `gf` isn't intended to be used in this way anyway.

**Comment by lervag** [comment]
For me, it returns a slightly different error which is less "intrusive":

```
E447: Can't find file "include" in path
```

Did you update vimtex?

**Comment by HawkinsT** [comment]
Yep. Just deleted and redownloaded my version of vimtex to be sure. Possibly an issue with windows file handling specifically since that's what I'm testing this on?

**Comment by lervag** [comment]
Yes, this could be an issue particular to Windows. I don't use Windows myself, so it is difficult to debug further. Sorry. If I saw an easy way to "fix" it and allow `gf` on the preceding white space, I would do it. But I don't see that, and so I propose to leave this as is. Pragmatically, it feels like this mostly works as it should, and that the failing case is easily coped with by pressing `w` first.

Or?

**Comment by HawkinsT** [comment]
No problem; I agree that it doesn't seem like an error worth spending much time over since `gf` is now working as intended. If find the time in the next few weeks I'll maybe take a look myself and issue a pull request if I come up with anything.

**Comment by lervag** [comment]
Great, I'll be happy to consider a PR if you should find a way to improve it!

**Comment by krishnakumarg1984** [comment]
err. I have the same issue on my macOS as well.

**Comment by lervag** [comment]
> err. I have the same issue on my macOS as well.

Noted. However, I don't use MacOS either, and so I can't do anything more. You should not use `gf` on the preceding whitespace anyway.
