### ISSUE TITLE
Vimtex: Viewer cannot find Zathura window ID

### ISSUE THREAD

**Issue by paulrougieux** [lervag/vimtex#1719]
I used **minimal.vim** with the 'zathura' viewer:
  ```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
" Use zathura as a PDF viewer
let g:vimtex_view_method = 'zathura'
  ```
and **minimal.tex**
  ```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
  ```
I started vim with 
```bash
    vim -u minimal.vim minimal.tex
```

**Commands/Input**
I called `:vimtexView` while editing minimal.tex.

**Observed Behaviour**
When launching :VimtexView I can see the following error message:

    vimtex: Viewer cannot find Zathura window ID!

And the focus stays on vim. If I close the Zathura window, and call the `:vimtexView` again, it is displayed correctly the first time althogh the error message is still displayed. Then if I just call the command another time, the focus doesn't jump to the zathura window and the error message is displayed again.

**Expected Behaviour**
I expect the command `:VimtexView` to jump the focus to the Zathura viewer. 

**Output from VimtexInfo**
```
System info
  OS: Debian GNU/Linux 10 (buster)
  Vim version: VIM 8.1 (1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401)
  Has clientserver: false

vimtex project: minimal
  base: minimal.tex
  root: /tmp/vimtexissue
  tex: /tmp/vimtexissue/minimal.tex
  out: /tmp/vimtexissue/minimal.pdf
  log: /tmp/vimtexissue/minimal.log
  aux: /tmp/vimtexissue/minimal.aux
  fls: /tmp/vimtexissue/minimal.fls
  main parser: current file verified
  compiler: latexmk
    backend: jobs
    output: /tmp/vULXQPT/2
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Zathura
    xwin id: 0
    process:
      pid: -
      cmd: zathura -x "/usr/bin/vim.nox --servername  --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class: minimal
~
```

In addition Zathura version:
```
 zathura --version
zathura 0.4.3
girara 0.3.2 (runtime: 0.3.2)
(plugin) pdf-poppler (0.2.9) (/usr/lib/x86_64-linux-gnu/zathura/libpdf-poppler.so)
```

This issue is related but different to #1117.

**Comment by paulrougieux** [comment]
Ah ok sorry now I see the help file:
```
  vimtex requires either nvim, Vim with +job, or vimtex-clientserver for the
  callback functionality to work. 
```

**Comment by paulrougieux** [comment]
I now installed vim with +clientserver support and started it with:
```
vim --servername VIM -u minimal.vim minimal.tex
```
The command `:VimtexView` still displays the error `vimtex: Viewer cannot find Zathura window ID!`

**Comment by lervag** [comment]
Do you have `xdotool` installed?

**Comment by paulrougieux** [comment]
Yes
>  sudo apt install xdotool
> ...
> xdotool is already the newest version (1:3.20160805.1-4).

**Comment by lervag** [comment]
Ok. After you do `\lv` to open Zathura, can you do the following and report the output?

1. Open a terminal.
2. Type `xdotool search --class Zathura`

It should output something like this:

```
> xdotool search --class Zathura
50331649
50331651
```

**Comment by paulrougieux** [comment]
Thanks for your reply.

> xdotool search --class zathura


# Doesn't show any output

However there is an output when I remove the --class parameter
> xdotool search  zathura


Defaulting to search window name, class, and classname


31457334

Also search by pid doesn't seem to work:
> ps aux |grep zathura


paul     24684  0.6  0.5 473680 43548 pts/8    Sl+  09:25   0:00 zathura -x
/usr/bin/vim.gtk --servername VIM --remote-expr
"vimtex#view#reverse_goto(%{line}, '%{input}')" --synctex-forward
> xdotool search --pid  24684
# Returns no result

I have xdotool version 3.20160805.1

**Comment by lervag** [comment]
Note, I think you need the capitalized version, `Zathura`, for the class search.

If you do `xprop` in a terminal, then select the Zathura window, what is the output? For me, it shows something like this:

```
_NET_WM_USER_TIME(CARDINAL) = 92796543
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_STICK, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
_NET_WM_DESKTOP(CARDINAL) = 1
_FLUXBOX_GROUP_LEFT(WINDOW): window id # 0x0
....
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x5200010
		bitmap id # of mask for icon: 0x520001b
		window id # of group leader: 0x5200001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 800, 1080
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 85983237, 85983238
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x5200004
WM_CLIENT_LEADER(WINDOW): window id # 0x5200001
_NET_WM_PID(CARDINAL) = 3084678
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "lotti"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 0 by 0
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "org.pwmt.zathura", "Zathura"
WM_ICON_NAME(STRING) = "org.pwmt.zathura"
_NET_WM_ICON_NAME(UTF8_STRING) = "org.pwmt.zathura"
WM_NAME(STRING) = "org.pwmt.zathura"
_NET_WM_NAME(UTF8_STRING) = "org.pwmt.zathura"
```

(I've removed some content to make things more condense). Note the `WM_CLASS` field that contains `Zathura`.

**Comment by paulrougieux** [comment]
I cannot select the Zathura window with xprop. I can however select other windows such as Firefox. 
I have tried using the `xprop -id`. But `xdotool search Zathura` returns an id that corresponds in fact to a Firefox tab. I guess this output from `xprop -id 31457334` is irrelevant. It has `WM_CLASS(STRING) = "Navigator", "Firefox-esr"`

Also the Zathura window appears with an exclamation mark when I press alt tab, I'm not sure if that's an issue, I'm using the Gome desktop.

**Comment by lervag** [comment]
Huh, in this case I have no idea what's going on. Does it work with `xwininfo`?

**Comment by paulrougieux** [comment]
`xwininfo` doesn't work either.

However if I start zathura with `GDK_BACKEND=x11 /usr/bin/zathura "$@"` as suggested in #744.
Both `xwininfo` and `xprop` work.
Here is the output of xprop:
```
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x3000010
		bitmap id # of mask for icon: 0x300001b
		window id # of group leader: 0x3000001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 8, 0, 784, 8, 0, 8, 800, 592
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 50331653, 50331654
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3000004
WM_CLIENT_LEADER(WINDOW): window id # 0x3000001
_NET_WM_PID(CARDINAL) = 3530
WM_LOCALE_NAME(STRING) = "en_IE.UTF-8"
WM_CLIENT_MACHINE(STRING) = "castanea"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 0 by 0
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "zathura", "Zathura"
WM_ICON_NAME(STRING) = "zathura"
_NET_WM_ICON_NAME(UTF8_STRING) = "zathura"
WM_NAME(STRING) = "zathura"
_NET_WM_NAME(UTF8_STRING) = "zathura"
```
Now I have to figure out how to make this the default so that vim starts zathura with `GDK_BACKEND=x11`.

**Comment by lervag** [comment]
Ah, you are on Wayland, then?

In any case, #744 also suggests to create a wrapper script for Zathura to apply the `GDK_BACKEND=x11`. Did you try that?

**Comment by paulrougieux** [comment]
When I open minimal.tex in vim with:
```
GDK_BACKEND=x11 vim --servername VIM -u minimal.vim minimal.tex
```
Then enter the command `:VimtexView` the error message mentioned in the title of this issue (cannot find Zathura window ID) is not displayed. The zathura windows opens on the first call to `VimtexView`. If I leave it open, edit in vim again and press `:VimtexView` again, the error message is not shown but the focus still doesn't jump to the zathura window.

Here is now the output of xdotool search: 
```
 xdotool search --class Zathura                                                                                                                                
56623105                                                                                                                                                                                      
56623107                        
```

**Comment by lervag** [comment]
Does it do the forward search as expected? I.e., does the second invocation of `\lv` make Zathura change the view to show the text corresponding to the location in Vim?

**Comment by lervag** [comment]
I think your suggested solution in #744 is better than prepending `GDK_BACKEND` to the Vim command itself.

**Comment by paulrougieux** [comment]
I am now using the zathura wrapper script as suggested in #744. 

> Does it do the forward search as expected? 
> I.e., does the second invocation of \lv make Zathura change the view 
> to show the text corresponding to the location in Vim?

Yes the forward search is working. But the zathura window still doesn't get the focus. That's OK when I'm on a large screen or dual screen setup. Of course on a laptop the zathura window is behind my terminal and it would be nice if it gets the focus after `:VimtexView` was called.

**Comment by lervag** [comment]
My initial thought is that the focus issue is due to Wayland vs X.

One possible solution is to use `xdotool` in a hook function. E.g., try this:

```vim
function! ZathuraHook() dict abort
  if self.xwin_id <= 0 | return | endif

  silent call system('xdotool windowactivate ' . self.xwin_id . ' --sync')
  silent call system('xdotool windowraise ' . self.xwin_id)
endfunction

let g:vimtex_view_zathura_hook_view = 'ZathuraHook'
```

**Comment by paulrougieux** [comment]
Thanks a lot for your dedication. Adding the hook function you provided to my `.vimrc` does fix the issue. Now calling `:VimtexView` does bring the focus to the zathura window.

**Comment by lervag** [comment]
Great, happy to hear it. I don't know why it didn't work in the first place, but at least good to know that sufficient customization to make it work already exists :)

**Comment by paulrougieux** [comment]
Thanks there were 3 steps involved:
1. Installing a version of vim that supports +clientserver
2. Adding a wrapper script so zathura starts in X11 and not in wayland
3. Adding  a hook function to `.vimrc` so that `xdtool` activates the zathura window correctly

**Comment by Char-Aznable** [comment]
I have the same issue but the solution provided here is deprecated due to deprecation of `vimtex_view_zathura_hook_view`. What is the current workaround for this?

**Comment by lervag** [comment]
You can do something like this:

```vim
function! ZathuraHook() dict abort
  if self.xwin_id <= 0 | return | endif

  silent call system('xdotool windowactivate ' . self.xwin_id . ' --sync')
  silent call system('xdotool windowraise ' . self.xwin_id)
endfunction

augroup vimrc_vimtex
  autocmd!
  autocmd User VimtexEventView call ZathuraHook()
augroup END
```

**Comment by Char-Aznable** [comment]
@lervag Thanks for the suggestion but your code give this error on forward search:
```
Error detected while processing User Autocommands for "VimtexEventView":
E725: Calling dict function without Dictionary: ZathuraHook
```

**Comment by lervag** [comment]
Sorry, I think it should work now.

**Comment by Char-Aznable** [comment]
Now it doesn't choke on the E725 error but I still get the `cannot find Zathura window ID` error.  In a combination of system package upgrade, forward and backward search is not workign with Zathura now. Any hint on how to fix all these?

**Comment by lervag** [comment]
Let me fix your config. First, you should _not_ mix the `Plug` lines with configuration. Put all the configuration of plugins _after_ the `call plug#end()`. This is important because some plugins rely on the use of function calls for configuration, which won't work until the `plug#end()` function is called.

So:

```vim
Plug 'lervag/vimtex'
" ...
call plug#end()
" ...

let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_ignore_filters = [
      \ 'Underfull \\hbox (badness [0-9]*) in paragraph at lines',
      \ 'Overfull \\hbox ([0-9]*.[0-9]*pt too wide) in paragraph at lines',
      \ 'Underfull \\hbox (badness [0-9]*) in ',
      \ 'Overfull \\hbox ([0-9]*.[0-9]*pt too wide) in ',
      \ 'Package hyperref Warning: Token not allowed in a PDF string',
      \ 'Package typearea Warning: Bad type area settings!',
      \]

function! ZathuraHook() abort
  if exists('b:vimtex.viewer.xwin_id') && b:vimtex.viewer.xwin_id <= 0
    silent call system('xdotool windowactivate ' . b:vimtex.viewer.xwin_id . ' --sync')
    silent call system('xdotool windowraise ' . b:vimtex.viewer.xwin_id)
  endif
endfunction

augroup vimrc_vimtex
  autocmd!
  autocmd User VimtexEventView call ZathuraHook()
augroup END
```

Note:

* You no longer need `let g:polyglot_disabled`, because polyglot no longer have any LaTeX plugins.

* No need to use the `if has_key(g:plugs ...` conditional.

However, I can not see anything wrong with your configuration that should lead to the error. Did you remember to update your plugins and vimtex in particular?

The error you are seeing, is it the same as in the original post? Would you mind opening a new issue for it with a new, clear description with a minimal vimrc? I know it is somewhat inconvenient, but it would be very helpful to me so that I don't spend too much time re-reading all of the irrelevant content in this thread.

**Comment by Char-Aznable** [comment]
It's the same error as in the OP. I opened a new issue here: https://github.com/lervag/vimtex/issues/1806
