### ISSUE TITLE
VimtexCompileSelected with \input in preamble

### ISSUE THREAD

**Issue by tbsmn** [lervag/vimtex#1915]
Hi first of all thanks for this great tool.

I ran in some issue when using the VimtexCompileSelected feature when using the `\input` command in my preamble.

For example I use `\input{config}` in my preamble to load some custom commands (e.g.`\newcommand{}`).

When I run VimtexCompileSelected the content of the file from `\input` (in this case config.tex) is copied in the temporary tex file, but the input command is also in this file resulting in a duplication which causes errors (in this case: command already defined).

Any idea how I could work around this?

**Comment by lervag** [comment]
Can you provide a minimal example of this particular case?

**Comment by tbsmn** [comment]
Sure.
I have a main.tex file that looks like this

```
\documentclass{scrreprt} 
\input{config}
\begin{document}
\textbf{\myTitle} 
This is a minmal example.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
\end{document}
```
And in the same folder a config file (config.tex) that looks like this for example:
`\newcommand{\myTitle}{Text of the title}`

When Selecting the Line "This is a minmal example" and unsing VimtexCompileSelected, this results in a main_vimtex_selected.tex that looks like this

```
\documentclass{scrreprt} 
\input{config}
\newcommand{\myTitle}{Text of the title}
\begin{document}
This is a minmal example.
\end{document}
```
Which leads to this error message when compiled:
```
main_vimtex_selected.tex|| Command \myTitle already defined.
main_vimtex_selected.tex|| Emergency stop.
main_vimtex_selected.tex|| ==> Fatal error occurred, no output PDF file produced!
```

**Comment by lervag** [comment]
This does not occur on my end. If I use the exact same file contents and the specified procedure, the resulting `main_vimtex_selected.tex` looks like this:

```tex
\documentclass{scrreprt}
\newcommand{\myTitle}{Text of the title}
\begin{document}
This is a minmal example.
\end{document}
```

Are you on the latest version of Vimtex? Can you provide the output of `:VimtexInfo`?

**Comment by tbsmn** [comment]
Oh sorry my fault. You are totaly right. I updated Vimtex and now it works! Perfect!
Thank you for the help!

I have one more question. Is there a way? To open the main_vimtex_selected.pdf automaticaly after compiling? For me this works on `:VimtexCompileSS` with the main.pdf but it is not working with `:VimtexCompileSelected`

Here is my output from `:VimtexInfo`
```
System info
  OS: Mac OS X 10.14.6 (18G7016)
  Vim version: VIM 8.2 (1-2164)
  Has clientserver: true
  Servername: VIM

vimtex project: main
  base: main.tex
  root: /Users/*****/sandbox/minimal_vimtex
  tex: /Users/*****/sandbox/minimal_vimtex/main.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  source files:
    main.tex
    config.tex
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      build_dir: build
      latexmk options:
        -synctex=1
        -verbose
      latexmk engine: -pdf
    job: process 20284 dead
    pid: 20284
    cmd: max_print_line=2000 latexmk -synctex=1 -verbose -pdf -outdir=build 'main.tex'
  viewer: Skim
    process: 
      pid: -
      cmd: osascript -e 'set theFile to POSIX file "/Users/*****/sandbox/minimal_vimtex/build/main.pdf"' -e 'set thePath to POSIX path of (theFile as alias)' -e 'tell application "Skim"' -e 'try' -e 'set theDocs to get documents whose path is thePath' -e 'if (count of theDocs) > 0 then revert theDocs' -e 'end try' -e 'open theFile' -e 'end tell' >/dev/null 2>&1 &
  qf: LaTeX logfile
    root: /Users/*****/sandbox/minimal_vimtex
    addqflist: 343
    errorformat_saved: 
    fix_paths: 344
    main: /Users/*****/sandbox/minimal_vimtex/main.tex
    set_errorformat: 342
  document class: scrreprt
  packages:
    keyval
    scrbase
    scrkbase
    scrlfile
    tocbasic
    typearea
```

**Comment by tbsmn** [comment]
I just realized that after the Pluginupdate `:VimtexCompileSelected` only compiles the first line of the selection. Is this intended?

**Comment by lervag** [comment]
Sorry, there was an error. It should be fixed now. Notice that you also have the mapping `\lL` which works both on the current visual selection and as an operator (e.g. `\lL}` to compile the following paragraph).

**Comment by tbsmn** [comment]
Thank you for mentioning this command, works for me.
And thanks for the great support. This is an awsome tool!!!

Is there a way to open the main_vimtex_selected.pdf automaticaly after compiling? For me this works on `:VimtexCompileSS` with the main.pdf but it is not working with `:VimtexCompileSelected`

If i use `\lL` on a paragraph vim still opens the main.pdf

**Comment by lervag** [comment]
> Thank you for mentioning this command, works for me.
> And thanks for the great support. This is an awsome tool!!!

Happy you find it useful! :)

> Is there a way to open the main_vimtex_selected.pdf automaticaly after compiling? For me this works on `:VimtexCompileSS` with the main.pdf but it is not working with `:VimtexCompileSelected`
>
> If i use `\lL` on a paragraph vim still opens the main.pdf

For me, this already works. Again, could you provide a minimal example, including the vimrc? I.e., the vimtex configuration is imporant here, I think.

**Comment by tbsmn** [comment]
Sure the latex example is the same as above. In my .vimrc I have this

```
let g:airline#extensions#vimtex#enabled = 1

if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
endif

au VimEnter * let g:ycm_semantic_triggers.tex=g:vimtex#re#youcompleteme

let g:vimtex_compiler_latexmk = {'build_dir' : 'build', 'options' : ['-synctex=1', '-verbose']}
let g:vimtex_view_method = 'skim'
let g:vimtex_view_automatic = 1
let g:vimtex_view_skim_activate = 1

let g:vimtex_indent_lists = [
    \ 'itemize',
    \ 'description',
    \ 'enumerate',
    \ 'thebibliography',
    \ 'aenumerate',
    \ 'compactitem',
    \ 'compactenum',
    \]

let g:vimtex_toc_config = {
            \ 'name' : 'TOC',
            \ 'layers' : ['content', 'todo'],
            \ 'resize' : 1,
            \ 'split_width' : 50,
            \ 'todo_sorted' : 0,
            \ 'show_help' : 1,
            \ 'show_numbers' : 1,
            \ 'fold_enable' : 1,
            \ 'fold_level_start' : 1,
            \ 'mode' : 2
            \}

```

**Comment by lervag** [comment]
Thanks! I'm quite sure this might be related to using Skim.

@clason I think you're the main "author" of the Skim viewer code (at least the osascript). Can you test if you can reproduce the problem mentioned by @tsmn in that `:VimtexCompilerSelected` does not open the viewer after compilation?

**Comment by clason** [comment]
Yes, I can confirm that. It seems that the script defaults to `main.pdf` even for selections.

**Comment by clason** [comment]
Never mind, it works the second time, so it's probably not the viewer itself. Maybe a race condition?

**Comment by clason** [comment]
`VimtexInfo` after `:VimtexCompilerSelected` from a clean directory:
```
System info
  OS: macOS 11.2 (20D5029f)
  Vim version: NVIM v0.5.0-dev+1012-gfe1ebea33
  Has clientserver: true
  Servername: /var/folders/02/1c5nlx115gj3hh6ft8zddfkm0000gn/T/nvimM1svNS/0
                                                                                                              vimtex project: main                                                                                            base: main.tex
  root: /Users/clason/test
  tex: /Users/clason/test/main.tex
  out:
  log:
  aux:
  fls:
  main parser: current file verified
  source files:
    main.tex
    config.tex
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Skim
  qf: LaTeX logfile
    addqflist: 56
    fix_paths: 57
    set_errorformat: 55
  document class: scrreprt
  ```
The temporary files (`main_vimtex_selected.*`) are correctly created, though.

If I then do `:VimtexCompilerSelected` a second time (with the temporary files in place), I get 
```
System info
  OS: macOS 11.2 (20D5029f)
  Vim version: NVIM v0.5.0-dev+1012-gfe1ebea33
  Has clientserver: true
  Servername: /var/folders/02/1c5nlx115gj3hh6ft8zddfkm0000gn/T/nvimM1svNS/0

vimtex project: main
  base: main.tex
  root: /Users/clason/test
  tex: /Users/clason/test/main.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  source files:
    main.tex
    config.tex
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Skim
    process: 
      pid: -
      cmd: osascript -e 'set theLine to 5 as integer' -e 'set theFile to POSIX file "/Users/clason/test/main_vimtex_selected.pdf"' -e 'set thePath to POSIX path of (theFile as alias)' -e 'set theSource to POSIX file "/Users/clason/test/main.tex"' -e 'tell application "Skim"' -e 'try' -e 'set theDocs to get documents whose path is thePath' -e 'if (count of theDocs) > 0 then revert theDocs' -e 'end try' -e 'open theFile' -e 'tell front document to go to TeX line theLine from theSource showing reading bar true'  -e 'end tell' >/dev/null 2>&1 &
  qf: LaTeX logfile
    root: /Users/clason/test
    addqflist: 56
    errorformat_saved: 
    fix_paths: 57
    main: /Users/clason/test/main_vimtex_selected.tex
    set_errorformat: 55
  document class: scrreprt
```
If I then compile a _different_ selection, I'm back at square one (no update of the PDF; I have to compile twice).

**Comment by lervag** [comment]
Ah, there's a regression. I think it's fixed now, please test.

**Comment by clason** [comment]
Yep, works now as expected! 💯

**Comment by tbsmn** [comment]
Still not working here. But I found, that I can set skim update the file on change. So I habe to open it once manually and then it will refresh on change. I'm totally fine with this workaourund.

Thanks for your help!!! This makes working with large documents so much better!

**Comment by lervag** [comment]
@clason Does it work for you with Skim? If I understood correctly, both of you and @tbsmn should have similar setups, so I don't understand why it does not work as expected on @tbsmn's end. Still, glad to hear it is already better, in any case.

**Comment by clason** [comment]
@lervag Yes, with Skim of course.
