### ISSUE TITLE
Running `:PackerSync` with vimtex causes neovim to crash

### ISSUE THREAD

**Issue by thatonemailbox** [lervag/vimtex#2724]
### Description

I use Neovim, and I use [packer](https://github.com/wbthomason/packer.nvim) to install and manage my plugins. I have the following code in my "plugins.lua":
```
return packer.startup(function(use)

	use "wbthomason/packer.nvim"
	use "nvim-lua/popup.nvim"
	use "nvim-lua/plenary.nvim"
	use 'lervag/vimtex'

end)
```
If I run `:PackerSync` with any other plugin, everything will be fine; but if I include the line 	`use 'lervag/vimtex'`, Neovim will crash after every sync.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: LAPTOP-7RC87GHR (Microsoft Windows 11 Home)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: \\.\pipe\nvim.16888.0

VimTeX project: test
  base: test.tex
  root: C:\Users\danim\Desktop
  tex: C:\Users\danim\Desktop\test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```

**Comment by lervag** [comment]
This sounds like a packer problem, not a VimTeX problem. I suggest you open this issue on the packer issue tracker instead. I have no idea why neovim would crash, and I don't believe there are any problems related to VimTeX that causes this.

**Comment by thatonemailbox** [comment]
@lervag Got it. I posted about it here: https://github.com/wbthomason/packer.nvim/issues/1240. I'm going to try reinstalling neovim to see what the issue is.

**Comment by thatonemailbox** [comment]
I'll give it a try. I usually follow other people's tutorials for setting up Neovim, and they usually use packer. But I like the idea of lazyloading, so I'll give it a shot!

**Comment by lervag** [comment]
lazy.nvim has become very popular lately, though, and I know a lot of people have swithed over from packer already. So you will probably find that recent tutorials are starting to suggest lazy.nvim instead of packer. ;)

**Comment by thatonemailbox** [comment]
Update: I tried with lazy.nvim, and I'm getting a similar issue--in fact, lazy is giving me more details:
![image](https://github.com/lervag/vimtex/assets/127370142/9d1a20a8-7d88-4fcf-ba97-99df63b5eac1)
I tried following the instructions giving by the error messages, and this is what happened:
![image](https://github.com/lervag/vimtex/assets/127370142/c512d258-8bf3-4dd1-ba93-f539b4e43796)

I'm only a beginner at git (at best), so I can't say I know what these error messages mean. But I will say that this situation is similar to what was happening with Packer: vimtex installs to 100%, and then something goes wrong. What could be going on  here?

**Comment by lervag** [comment]
My suggestion would be to simply delete the vimtex folder and install it again.

**Comment by lervag** [comment]
Hahaha; the solution is to stop using Windows, because Windows is stupid! See here: https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl

I've pushed a commit that I think may solve this. Try and delete vimtex and clone again.

**Comment by thatonemailbox** [comment]
> Hahaha; the solution is to stop using Windows, because Windows is stupid! See here: https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl
> 
> I've pushed a commit that I think may solve this. Try and delete vimtex and clone again.

Sad to say that the issue still hasn't gone away when using packer, but vimtex now installs to completion on lazy! Thanks for your persistence on this issue!

**Comment by lervag** [comment]
> Sad to say that the issue still hasn't gone away when using packer,

I checkout out your config and tried to reproduce, but on my end, everything seems to work as expected. I'm on the nightly neovim on Linux, though, so this may definitely be a factor here.

> but vimtex now installs to completion on lazy! Thanks for your persistence on this issue!

That's good to hear! I would suggest that you use lazy, then. :)
