### ISSUE TITLE
[Bug] Can't jump from included file to included bib-file

### ISSUE THREAD

**Issue by benutzer193** [lervag/vimtex#518]
### Explain the issue

I just encountered a strange bug. If I have a bib file and included files in the ToC I am not able to jump AND close (meaning Enter jump; space jump works) from included file to bib file.

Everything else is working as expected:

- bib to included
- entry like preamble to bib
- ...

**Comment by lervag** [comment]
Can you provide a minimal example?

**Comment by benutzer193** [comment]
yeah sure:

main.tex
```
\documentclass[a4paper,12pt]{scrartcl}
\input{tex/commands}
\addbibresource{bib/main.bib}

\begin{document}
\include{tex/1}

\end{document}
```


./bib/main.bib

```
@article{test,
    author={test},
    title={test},
    journaltitle={test},
    volume={1},
    number={1},
    year={1999},
    pages={1--99}
}
```

./tex/commands.tex
```
% commands
\newcommand{\tt}{test}
```

./tex/1.tex
```
%TODO
%
```

I just found another bug/feature creating this minimal example:
A included file needs at least 2 lines or it won't be added to the ToC.
(should be at least mentioned in the help file.)

If you wonder for which situations one could have one or less lines in a file,
I have some templates with empty files (part1,2,3,...).

**Comment by lervag** [comment]
I think it is solved now, please test.

**Comment by benutzer193** [comment]
It does not fix the problem for me (tested with minimal example).
But now I get the following error message, when I open the ToC:

```
Error detected while processing function vimtex#toc#open[10]..vimtex#toc#get_entries[69]..<SNR>74_parse_bib_input[8]..vimtex#util#kpsewhich:
line 1:
E172: Only one file name allowed: lcd /home/*****/Documents/Templates/minimal
line 6:
No previous directory
```

**Comment by lervag** [comment]
Thanks. I already thought about adding the `fnameescape`, but I was not sure it was necessary.
