### ISSUE TITLE
Freezing when exiting insert mode in large files.

### ISSUE THREAD

**Issue by tbrosnan** [lervag/vimtex#52]
This is something I've noticed recently, if I edit a large latex file (several hundred lines, with no wrapping, so lines can be very long) I see a delay of 1-3s when exiting insert mode. CPU usage for gvim hits 50% (I'm using a dual-core) during this time.

Disabling folding and syntax highlighting doesn't change things. If I disable the plugin and edit the file using vim's default latex support it is instant again.

I see a similar delay when opening a large file for the first time - again, default vim works fine.

Here is the result of `:au InsertLeave`:

```
--- Auto-Commands ---
Undotree  InsertLeave
    *         call UndotreeUpdate()
unimpaired_paste  InsertLeave
    *         if exists('s:paste') |   let &paste = s:paste |   let &mouse = s:mouse |   unlet s:paste |   unlet s:mouse | endif
latex_fold  InsertLeave
    *.tex     call FdmRestore()
```

`FdmRestore()` just seems to track folding methods so I don't think this would be the problem.

It seems like some sort of processing of text that vim-latex is doing, for folding maybe? I do not even needed to make any changes, entering and immediately exiting insert mode will trigger a delay.

**Comment by mihaelS** [comment]
Hello! 
Seems vimtex#fold#level() is very slow..
in vimrc I set g:latex_fold_automatic = 0, but it doesn't help.
Is there some work around?

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
128220             19.237260  vimtex#fold#level()
  922              0.028393  airline#highlighter#exec()
    7   0.094512   0.026499  airline#highlighter#highlight()
  756              0.019257  <SNR>162_get_syn()
    2              0.014834  <SNR>153_check_mixed_indent()

**Comment by lervag** [comment]
First, all `vimtex` options now start with `g:vimtex_...`.

Could you please provide the full set of options you are using? With `g:vimtex_fold_automatic = 0`, which is now the default value, the fold level function should only be run by the user manually through `zx`.

Which version of vimtex are you using?

**Comment by mihaelS** [comment]
1. It slows down when I'm printing text in insert mode.

2. It is slow only when I'm editing tex file  and there is other 5 large tex files is opened in a buffers. I  open all files from a session file (:mks tex_files.mks;   vim -S tex_files_mks)

3. It is working pretty fast, when I'm openning a single tex file.

4. here is vim settings in the slow file https://gist.github.com/mihaelS/32bc3b1127f9ff15567a

5. I think there is the last version (current) I'm updating regulary.
The last lines in the chenge log:
2015-06-06: Minor but convenient restructuring (++)~
I've changed a lot of the code structure in relatively small ways.  For
instance, instead of referring to the particular data blobs through the global
array, I instead linked a buffer variable to the correct global array element.
...

**Comment by lervag** [comment]
Based on your settings you do not set any options for vimtex. Note that your vimrc file is quite messy and difficult to parse visually. Also, I [see](https://gist.github.com/mihaelS/32bc3b1127f9ff15567a#file-gistfile1-txt-L971) you add plugins manually, instead of through a plugin manager. This might work as expected, but it might also not. For instance, I would recommend you instead do:

```vimL
let &rtp = '~/.vim/plugged/<bundle>,' . &rtp
```

for each `<bundle>` or plugin. Also, `vim-latex` changed the name to `vimtex` several months ago. I guess github still redirects `vim-latex` automatically to `vimtex`, but I don't know how long that works. And I notice you add both `vim-latex` and `vim-latex/after`. The latter is not necessary, as it is implied by the former.

What happens if you open the tex files in a fresh session (not loaded from a session file)?

Which version of Vim are you using?

**Comment by mihaelS** [comment]
I'm using  'vim-plug'  pluggin manager, so it install the vimtex. So I changed:
Plug 'lervag/vimtex'
Seems that it is  installed correctly.

When I'm using fresh session,  it just work fast. As way as it should. No hang up after  every tap on the keyboard .
1)After deliting all other buffers in the old session  text inset is still slow.
2) After reload .vimrc in the old session  text insert is still slow.

vim version is 7.4.52

**Comment by lervag** [comment]
What happens if you create a new session similar to your old session?

I can not say why it is slow in the old session, but my suspicion is that the old session somehow still uses the automatic folding, regardless of the contents in your vimrc file.

**Comment by mihaelS** [comment]
I made several tests:
1. open tex files in the NewSession1 in the old order.  Inserting text is slow.
2. open tex files in the NewSession2 in desc order. Inserting text is fast. Then I save session. And open it. Inserting text is slow.

Result:
in the some files (not all) inserting text is critically slow. 
It appears in the files with more than 1000 lines (1000, 3000, 4000). Probably it depends on the files structure..

**Comment by lervag** [comment]
This is very strange. I don't really understand what is happening here.

So, if you open a single tex file, regardless of size, everything will be fast as expected. Right? The problem here is only when you open the files and use the session feature?

**Comment by mihaelS** [comment]
yes, working in a single file is fast.
I opened 2 most big files and save the session. Session was fast.
After adding the 3rd file the big one files begin to slow.
Lags appears in some lines positions -  closer to the end,  the greater the lags.

* I'm addiding the files in the new tabs.

**Comment by lervag** [comment]
Could you try again in a single file, but this time make sure it is a file with very long lines? The automatic folding feature is known to become very slow on long lines (which is one of the reasons I don't recommend that option and why it is not default).

Would you be able/willing to create a minimal working example and a minimal vimrc file that makes it possible for me to reproduce this, along with a description of how to reproduce? The minimal vimrc file should be something like this:

```vimL
set nocompatible
let &rtp = '~/.vim/plugged/vimtex,' . &rtp
filetype plugin indent on
syntax enable
" Add relevant vimtex options (if any)
```

If you are not able to reproduce the problem with a minimal example, then it would also work if you could share some files where the problem occurs.

**Comment by mihaelS** [comment]
Going to do it. I will post the results a bit later

**Comment by lahwaacz** [comment]
Some time ago, I also noticed problems with vimtex's folding and the `:mksession` command. Most notably, the state of the folds was not preserved, unlike other filetypes. I did not notice any slowdown in the restored session, so the problem might have been introduced in recent (~1 month) changes.

**Comment by lervag** [comment]
The last essential update was to parse modeline settings in early July. Before that I did some minor restructuring and similar things, but nothing that should change the fold feature directly. Of course, I may have introduced a bug.

In any case, until I have a clear issue that I can reproduce, I really can not help very much.

**Comment by mihaelS** [comment]
Hello! 

here is an example :
http://fileload.info/y6c256j403c8

Steps to reproduce it:
0. install vim-plug :
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

1. copy .vimrc from archive to homeDir
2. install pugins (in vim):
:PlugInstall

3. open test.tex files  from archive in separate tabs
vim -p test*teh

4. save session (in vim):
:mks m.mks

5. open session file
vim -S m.mks

6. try to type text (several sentences) at the end  of the .tex files. 
In some files there is lags.

**Comment by mihaelS** [comment]
Did the example is reproduced?

**Comment by lervag** [comment]
Yes, the example is reproducible. That is, I skipped the session part, steps 5 and 6, and I still verify the problem. I use the following minimal vimrc file when reproducing:

```vimL
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax enable
```

Then to reproduce, I open the tex files with `vim -u minivimrc -p test*tex`. Now I go to the last line and insert above the `\begin{document}`, and I experience the lag you are talking about.

My test indicates that the session is not relevant.

I tested further, and it seems to me that the tab window part is relevant. If I instead open with `vim -u minivimrc test*.tex`, where `minivimrc` also has `set hidden`, I do not experience the lag.

It would be helpful to know if my investigation matches your results so far.

**Comment by lervag** [comment]
Could I ask: The tex file seems very strange to me and has a lot of very strange signs, e.g. as shown below:

```tex
\documentclass[a4paper######,######]###{######}###
###%\usepackage{ifthen}######
\usepackage[utf8]{inputenc}######
\usepackage{gensymb}######
```

What are all the `#` signs for? Did you scramble the tex files before sharing?

**Comment by lervag** [comment]
I think I found the problem. It seems that when you open several files in tab pages, all of the buffers are loaded at once. For the manual fold mode, there is an autocommand that is created in order to ensure that the `&foldmethod` is `manual`; the autocommand self destructs when executed. Thus for the second buffer that is loaded, this autocommand has already self destructed and does not work.

I will try to find a fix.

**Comment by lervag** [comment]
Should be fixed now, please test.

**Comment by mihaelS** [comment]
Yes, I scrumble the file before posting.
Unfortunately, problem remain. Same example.

vimtex/autoload/vimtex/fold.vim:
```vim
    if g:vimtex_fold_automatic
      augroup vimtex_fold_automatic
        autocmd!
        autocmd InsertEnter <buffer> call FdmSave()
        autocmd InsertLeave <buffer> call FdmRestore()
      augroup END
    endif
  else
    augroup vimtex_fold_manual
      autocmd CursorMoved <buffer> call vimtex#fold#refresh('zx')
      autocmd CursorMoved <buffer> autocmd! vimtex_fold_manual
    augroup END
```

Results:
```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
111020             16.489066  vimtex#fold#level()
    2              0.013080  <SNR>165_check_mixed_indent()
  280              0.008321  <SNR>174_get_syn()
  250              0.007772  airline#highlighter#exec()
    3   0.031025   0.006955  airline#highlighter#highlight()
```

**Comment by lervag** [comment]
Interesting. I think I found the issue, but to be sure: Could you please remove the `vimtex_fold_manual` autocommand group and instead have only

```vimL
  else
    setlocal fdm=manual
  endif
```

I think this should remove the lag, but it will introduce a second problem: the folds are not activated properly. The point of the autocommand group is to ensure that the folds are refreshed upon startup.

I think I should investigate some more and find an alternative way to ensure that the folds are refreshed.

**Comment by mihaelS** [comment]
Yes, now it pretty fast! :+1: 
But,  folds crashed - I can not collapse the folds.

**Comment by lervag** [comment]
I've opened [a question](https://vi.stackexchange.com/questions/4280/run-function-for-filetype-after-buffer-has-opened) on [vi.stackexchange.com](https://vi.stackexchange.com/).

I also think I have a new solution that should work.

**Comment by lervag** [comment]
With the fix I mentioned you have to manually refresh the folds with `zx`. Then the folds should be collapsable.

**Comment by mihaelS** [comment]
Yes, got it. Thx !

**Comment by lervag** [comment]
Now it should be fixed. Please test.

**Comment by mihaelS** [comment]
Works perfect!  :100:

**Comment by lervag** [comment]
Great! Thanks for noticing and reporting the issue!
