### ISSUE TITLE
E684: list index out of range: 0 during auto-completion

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#531]
### Explain the issue

When I try to complete a reference by its counter, I sometimes experience errors like the following:

`
Error detected while processing function vimtex#complete#omnifunc[27]..5[3]..6[1]..7[11]..8:
line   20:
E684: list index out of range: 0
`

Similar errors occur sometimes when I try to auto-complete references by name using omni-completion.

I only observed this in large documents. Therefore I do not provide a minimal example.

**Comment by lervag** [comment]
I understand that it might be difficult to create a minimal working example. But unless you can explain how I can reproduce this, there is really not that much I can do...

Thus: Please provide a reproducible description of how to raise the error. The best thing is a minimal example, but I will also accept any working example.

**Comment by heiderich** [comment]
I have the impression that there is a problem when counters are formated using latin characters. For instance in the example below "thm:bar" is not found using "A.1" (only the error "Pattern not found" is shown).

I can reproduce the error described initially by trying to auto-complete "\cite{1" or "\cite{har" in the following example.   

`
documentclass{article}                                                

\usepackage{appendix}
\usepackage{amsthm}
\newtheorem{thm}{Theorem}[section]

\begin{document}

\section{Introduction}

\begin{thm}
        \label{thm:foo}
        foo
\end{thm}

\appendix

\section{An appendix}
\begin{thm}
        \label{thm:bar}
        bar     
\end{thm}

\begin{thebibliography}{Har77}
\bibitem[1]{hartshorne} Hartshorne, R.: {\it Algebraic Geometry}.
Graduate Texts in Mathematics 52, Springer (1977)
\end{thebibliography}

\end{document}
`

**Comment by lervag** [comment]
The problem was due to an error in the handling of items in the `thebibliography` environment. I think it should work now. Please test.

**Comment by heiderich** [comment]
I can now complete \cite{har

**Comment by heiderich** [comment]
I still experience the problem reported initially when trying to auto-complete a reference while the compilation is in progress (in big documents).

**Comment by lervag** [comment]
Regarding the `\cite{1` completion, this is  expected. Completion is based on regex-matching, and the number is not part of this. In particular, there is no parsing of `thebibliography` environments except the gathering of citation keys. This could  be improved, but I'd rather not, because `\bibitem` commands are not very parsable as far as I can understand. The order of authors, titles, etc., may be different based on the chosen bibliography style (be it manual or automatic). Thus, I consider the current version of the `\cite` completion to work as expected.

Again, you say you experience a problem with the reference completion, but I can not help unless you can provide a way for me to reproduce it.

Regarding `\ref{A.1`: This is label completion (i.e., it is not the same as citation completion). It does support completing by numbers, but `A.1` will not be a recognized expression. The reason for this is that I parse the `aux` file to get the reference number, where it is labelled `1.1`, not `A.1`. Thus, if you try to complete `\ref{1.1`, it will work. I know this is not optimal. But it is the best I can do. Sorry...

**Comment by lervag** [comment]
Note, though: I added `[thebibliography]` as a key to the completion menu to make it clear which citation entries come from `thebibliography` environments.

**Comment by heiderich** [comment]
I observed that the problem I described in my initial post occurs mostly (and probably only) while the compiler is running. It seems that it does not occur anymore after the compilation is finished. You may try to reproduce it by compiling a sufficiently large .tex file and trying to auto-complete a reference while the compilation is in process.

Without knowing the internals of vimtex, I would guess that it tries to read a file that is not yet (completely) written during compilation. If this is the case, could one make a copy of this file and use it for the auto-completion?

**Comment by lervag** [comment]
Ah, I see. Completion of labels are based on entries in the aux file. When compiling large documents, the aux file is not always available.

Fixing this is not that simple, because there are some edge cases. However, I'm pushing a minor tweak that I hope might help. If not, then I don't want to fix this, because it requires too much work. At least for now. :\
