### ISSUE TITLE
Quickfix buffer can't be closed by `\le` due to the a language-dependent variable

### ISSUE THREAD

**Issue by Aster89** [lervag/vimtex#861]
I'll skip the boring part, since the problem seems quite simple to me, except that I don't know how language-related problems have been solved so far.

The accused line is the `137`th in `autoload/vimtex/qf.vim`. In order to determine whether the quickfix buffer is open or not, `l:buflist` is checked against the string `Quickfix List` (in square brackets). The problem is that in my case the quickfix list is named `Lista Quickfix` (Italian).

I think that I can solve this by putting a proper line in `.vimrc`, but I've not been able to find which Vim variable the quickfix window's name is stored in. On the other hand, `VimTeX` should work independently of the language, shouldn't it?

If you give me a hint, maybe I could guess how to fix this bug.

**Comment by lervag** [comment]
I've fixed this. At least I think it should work now. I still have to rely on there being a window/buffer with a name that contains `Quickfix`, so the language dependent names are assumed to still use this name.

**Comment by Aster89** [comment]
@lervag , it still doesn't work for me.

Btw, when I debug vimscripts (I was trying with this script indeed), I make use of `echo` to see _e.g._ what variables contain what, but it seems that I cannot do that in that function (in did it already in other function of other files of vimtex). I thought it was due to the `abort` attribute of the function, which I then removed to make the debugging easier, but it didn't work. Any hint?

**Comment by lervag** [comment]
Sometimes you need to do `unsilent echo`. You can also do `ehcom` and then `:message` to see old messages. Further, in some cases the messages are cleared before you can see them. You can either add `sleep` statements, or you can instead do `let g:test = ...` and check test `g:test` afterwards.

If you are not able to find the problem yourself, then please provide a full minimal example and info on your system (OS, Vim version, etc). I'll try to reproduce again.

**Comment by Aster89** [comment]
Karl, I've just realized that on two different computers the behavior is different.
(I do not have a MWE, since the problem(s) shows independently with respect to the `TeX` file I use.)

1. On one computer (Linux Mint 18.1 Cinnamon 64bit, `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 03 2017 12:11:53)`):
- `\le` correctly opens and closes the quickfix window (whose name is `Lista Quickfix`, in italian);
- if I open a `*.tex` file (with an error in it) from a parent directory the quickfix window shows `./se2.tex|30 error| Undefined control sequence. { \huge \bfseres` if I open it by `\le`, or `se2.tex|30 error| Undefined control sequence. { \huge \bfseres` if I let it open with `\ll`; note the wrong path in both cases; indeed if I enter `:ls!` in the first case, I get
```
  1 %a   "Scrivania/prove-varie/se2.tex" riga 64
  2u     "se2.tex"                      riga 0
  3  a-  "[Lista Quickfix]"             riga 0
```
(in the second case the only difference is, again, `"./se2.tex"` instead of  `"se2.tex"`) and, when I go to the QW and press enter on the error, the active buffer/window becomes the 2nd one which is empty!
2. On a second computer (Ubuntu 16.04.2 LTS, `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)`):
- `\le` opens and does not close the QW
- The path in the QW is correct (`Scrivania/texprova/prova.tex|14 error| Undefined control sequence. \uffaScrivania/texprova/prova.tex|14 error| Undefined control sequence. \uffa`), but I still see (if I open the file from a parent dir) a wrong file in the list, indeed `:ls!` gives
```
  1 %a   "Scrivania/texprova/prova.tex" riga 12
  2u     "./prova.tex"                  riga 0
  3  a-  "[Lista Quickfix]"             riga 0
```

I'm not sure whether this strange behavior of opening a new buffer with the same name in the wrong path is somehow related to VimTeX or not, but I'm not sure of the opposit either :D

**Comment by lervag** [comment]
First, it seems we are now discussing multiple issues. Could we focus on one of them first (i.e. `\le` not closing the quickfix window), and the consider the other after (i.e. the one with quickfix paths)?

It is difficult for me to reproduce the mentioned problem, so I would be happy if you would be able to debug this yourself (with my help, of course).

I think the issue is located in the `s:qf_is_open` function. My suggestion is to add something like:

```vim
echom string(l:buflist)
" ...
echom l:bufnr bufwinnr(l:bufnr) ...
```
at relevant locations inside the function, and to see if the output is as expected.

**Comment by Aster89** [comment]
We can archive this issue.

The problem on Ubuntu was simply due to the old version of Vim I was using (7.4, if I correctly remember) which has no `:filter` command. I solved it by installing the most recent Vim8 release here on GitHub.

Now on both computers, I see the problem 1. I'll open another issue if I don't come to a solution in reasonable time.

**Comment by lervag** [comment]
Ah, I see. Thanks for your effort in finding the problem. Could you also state which sub version/patch version you were on? (Output from `:version`).

**Comment by Aster89** [comment]
No more, Karl, I'm so sorry (unless Ubuntu saves a sufficient number of terminal std output lines somewhere, but I don't think so...), although I'd bet a significant amount of money on 7.4., but I think you need more then an hazard player, ahahah 😂

Today's lesson for me: keep track of what's the last version presenting the problem.

**Comment by lervag** [comment]
Haha, no problem. But I guess you were using the Vim version from the standard repositories.

Also, I found that `:filter` was added in patch 7.4.2263. Perhaps it is better to avoid it, then. Else this issue will be there for everyone who uses e.g. Ubuntu 16 and lower.

**Comment by lervag** [comment]
I've just pushed an update that uses `filter()` instead of `:filter`. This should now work on your old configuration, I think.

**Comment by Aster89** [comment]
Yes, it was the standard repo version. No, I've removed it and installed the new one (following [YCM's Val's guide](https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source)).
